# Generated by Django 3.2.5 on 2021-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(max_length=200),
        ),
    ]
